name: "AchanYao/S3 Upload"
description: "Upload files and directories to S3 compatible cloud buckets"
author: "AchanYao <yyx1310059081@gmail.com>"
runs:
  using: docker
  image: Dockerfile
branding:
  icon: message-square
  color: gray-dark
